### ISSUE TITLE
The detail of data generation pipeline

### ISSUE THREAD

**Issue by secret104278** [OpenDriveLab/OpenScene#2]
Dear OpenDriveLab Team,
Thank you for sharing your outstanding work with the community. 
Will you public the details of your data generation pipeline? such as how you manage dynamic objects when merging multiple LiDAR frames in your data pipeline.
Thanks in advance.

**Comment by ZhouYunsong-SJTU** [comment]
Thanks for your interest. In order to ensure the iteration of the dataset, we currently do not have plans to release the code for data processing. However, for the process of occupancy generation, please refer to OccNet (https://github.com/OpenDriveLab/OccNet). We use box annotations to accumulate foreground objects and background point clouds separately.
